name: Despliegue a Producción

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Desplegar en Servidor de Producción
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar despliegue en el servidor vía SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SV_IP }}
          username: ${{ secrets.SV_USER }}
          password: ${{ secrets.SV_PASSWORD }}
          script: |
            set -e

            cd /var/www/encriptador

            docker compose exec unicripter php artisan down || true

            echo "-> Actualizando código desde Git de forma segura..."
            git fetch origin main
            git reset --hard origin/main
            echo "-> Reconstruyendo y reiniciando contenedor de la aplicación..."
            docker compose up -d --build --force-recreate --remove-orphans

            echo "-> Copiando archivo .env de producción al contenedor..."
            docker cp .env unicripter:/var/www/html/.env
            docker compose exec unicripter chown www-data:www-data /var/www/html/.env

            echo "-> Limpiando caché y ejecutando migraciones..."
            docker compose exec unicripter php artisan migrate --force
            docker compose exec unicripter php artisan optimize:clear

            echo "-> Desactivando modo mantenimiento..."
            docker compose exec unicripter php artisan up

            echo "-> Limpiando imágenes de Docker sin usar..."
            docker image prune -a -f

            echo "¡Despliegue completado!"
